on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref }} # get the tag name from the context
      RELEASE_NAME: Release ${{ github.ref }} # create a release name from the tag name
    steps:
      - name: Create Release
        id: create_release # give an id to this step
        uses: actions/create-release@v1 # use the create-release action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # provide the GitHub token as an environment variable
        with:
          tag_name: $env:TAG_NAME # use the tag name as an input
          release_name: $env:RELEASE_NAME # use the release name as an input
          draft: false # make the release not a draft
          prerelease: false # make the release not a prerelease